set(output_dir ${CMAKE_SOURCE_DIR}/out)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${output_dir}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${output_dir}/lib)
set(CMAKE_TESTS_OUTPUT_DIRECTORY ${output_dir}/tests)

set(PROTOFILES_DIRECTORY ${CMAKE_SOURCE_DIR}/proto)

set(GENERATED_DIRECTORY ${CMAKE_SOURCE_DIR}/generated)
set(GENERATED_GRPC_DIRECTORY ${GENERATED_DIRECTORY}/cpp/grpc)
